"""
Deep Vision 配置文件示例

使用说明：
1. 二选一：复制本文件为 config.py，或复制 .env.example 为 .env
2. 填入实际的 API Key 和业务配置
3. config.py / .env 都已加入忽略规则，不会提交到版本库

说明：
- 本示例采用当前项目推荐的模型分工：问题=MiniMax-M2.5，报告=claude-opus-4-6，摘要/搜索决策=glm-5。
- 报告 V3 默认使用 balanced 档，并启用双阶段路由：草案走 question lane，审稿走 report lane。
- 报告 V3 的时延/长度参数默认留空(None)，这样可按档位自动取值：balanced 更快，quality 更稳。
"""

# ============ 大模型 API 配置 ============

# 全局默认网关（未单独配置 QUESTION/REPORT/SUMMARY/SEARCH_DECISION 时回落到这里）
ANTHROPIC_API_KEY = "your-global-api-key"
ANTHROPIC_BASE_URL = "https://open.bigmodel.cn/api/anthropic"
ANTHROPIC_USE_BEARER_AUTH = True

# 模型配置
MODEL_NAME = "MiniMax-M2.5"  # 默认主模型（问题链路）
QUESTION_MODEL_NAME = MODEL_NAME
REPORT_MODEL_NAME = "claude-opus-4-6"
SUMMARY_MODEL_NAME = "glm-5"
SEARCH_DECISION_MODEL_NAME = SUMMARY_MODEL_NAME

# 问题与报告独立网关
# 问题链路建议放更快的模型；报告链路建议放更稳的高质量模型
QUESTION_API_KEY = "your-question-api-key"
QUESTION_BASE_URL = "https://api.minimaxi.com/anthropic"
REPORT_API_KEY = "your-report-api-key"
REPORT_BASE_URL = "https://api.aicodemirror.com/api/claudecode"

# 摘要与搜索决策独立网关
SUMMARY_API_KEY = "your-summary-api-key"
SUMMARY_BASE_URL = "https://open.bigmodel.cn/api/anthropic"
SEARCH_DECISION_API_KEY = "your-search-decision-api-key"
SEARCH_DECISION_BASE_URL = "https://open.bigmodel.cn/api/anthropic"

# Bearer 鉴权开关
# aicodemirror / minimax / 智谱 Anthropic 兼容网关通常都建议使用 Bearer
QUESTION_USE_BEARER_AUTH = True
REPORT_USE_BEARER_AUTH = True
SUMMARY_USE_BEARER_AUTH = True
SEARCH_DECISION_USE_BEARER_AUTH = True

# Token 限制配置
MAX_TOKENS_DEFAULT = 4000
MAX_TOKENS_QUESTION = 1600
MAX_TOKENS_REPORT = 7000
MAX_TOKENS_SUMMARY = 500

# AI 运行策略配置
API_TIMEOUT = 90.0
REPORT_API_TIMEOUT = 180.0
REPORT_V3_PROFILE = "balanced"  # 默认报告档位：balanced / quality

# 保持为 None 时，server.py 会按档位自动取默认值
REPORT_DRAFT_API_TIMEOUT = None
REPORT_V3_DRAFT_MAX_TOKENS = None
REPORT_V3_DRAFT_FACTS_LIMIT = None
REPORT_V3_DRAFT_MIN_FACTS_LIMIT = None
REPORT_V3_DRAFT_RETRY_COUNT = None
REPORT_V3_DRAFT_RETRY_BACKOFF_SECONDS = None
REPORT_V3_REVIEW_MAX_TOKENS = None
REPORT_V3_REVIEW_BASE_ROUNDS = None
REPORT_V3_QUALITY_FIX_ROUNDS = None

REPORT_V3_MIN_REVIEW_ROUNDS = 0  # 0=按档位默认(balanced=1, quality=2)
REPORT_V3_DUAL_STAGE_ENABLED = True
REPORT_V3_DRAFT_PRIMARY_LANE = "question"
REPORT_V3_REVIEW_PRIMARY_LANE = "report"
REPORT_V3_QUALITY_FORCE_SINGLE_LANE = False
REPORT_V3_QUALITY_PRIMARY_LANE = "report"
REPORT_V3_RENDER_MERMAID_FROM_DATA = True
REPORT_V3_WEAK_BINDING_ENABLED = True
REPORT_V3_WEAK_BINDING_MIN_SCORE = 0.46
REPORT_V3_SALVAGE_ON_QUALITY_GATE_FAILURE = True
REPORT_V3_FAILOVER_ENABLED = True
REPORT_V3_FAILOVER_LANE = "question"
REPORT_V3_FAILOVER_ON_SINGLE_ISSUE = True
REPORT_V3_BLINDSPOT_ACTION_REQUIRED_BALANCED = False
REPORT_V3_BLINDSPOT_ACTION_REQUIRED_QUALITY = True
REPORT_V3_UNKNOWNS_TO_OPEN_QUESTIONS_ENABLED = True
REPORT_V3_UNKNOWNS_TO_OPEN_QUESTIONS_MAX_ITEMS = 3
REPORT_V3_UNKNOWN_RATIO_TRIGGER = 0.65

CONTEXT_WINDOW_SIZE = 5
SUMMARY_THRESHOLD = 8
SUMMARY_UPDATE_DEBOUNCE_SECONDS = 60
SEARCH_DECISION_CACHE_TTL_SECONDS = 900
SEARCH_DECISION_CACHE_MAX_ENTRIES = 256
SEARCH_DECISION_INFLIGHT_WAIT_SECONDS = 10.0
SEARCH_RESULT_CACHE_TTL_SECONDS = 300
SEARCH_RESULT_CACHE_MAX_ENTRIES = 128
SEARCH_RESULT_INFLIGHT_WAIT_SECONDS = 12.0
PREFETCH_IDLE_ONLY = True
PREFETCH_IDLE_MAX_LOW_RUNNING = 0
PREFETCH_IDLE_WAIT_SECONDS = 8.0
FIRST_QUESTION_PREFETCH_PRIORITY_ENABLED = True
FIRST_QUESTION_PREFETCH_PRIORITY_WINDOW_SECONDS = 120.0
QUESTION_FAST_PATH_ENABLED = True
QUESTION_FAST_TIMEOUT = 12.0
QUESTION_FAST_MAX_TOKENS = 1000
QUESTION_FAST_LIGHT_PROMPT_MAX_CHARS = 1800
QUESTION_FAST_SKIP_WHEN_TRUNCATED_DOCS = True
QUESTION_FAST_ADAPTIVE_ENABLED = True
QUESTION_FAST_ADAPTIVE_WINDOW_SIZE = 20
QUESTION_FAST_ADAPTIVE_MIN_SAMPLES = 8
QUESTION_FAST_ADAPTIVE_MIN_HIT_RATE = 0.35
QUESTION_FAST_ADAPTIVE_COOLDOWN_SECONDS = 900.0
QUESTION_HEDGED_ENABLED = True
QUESTION_HEDGED_DELAY_SECONDS = 1.5
QUESTION_HEDGED_SECONDARY_LANE = "summary"  # 用 glm-5 做问题链路备用，避免让 Opus 抢答高频问题
QUESTION_HEDGED_ONLY_WHEN_DISTINCT_CLIENT = True
QUESTION_RESULT_CACHE_TTL_SECONDS = 180
QUESTION_RESULT_CACHE_MAX_ENTRIES = 512
METRICS_ASYNC_FLUSH_INTERVAL_SECONDS = 1.5
METRICS_ASYNC_BATCH_SIZE = 20
METRICS_ASYNC_MAX_PENDING = 5000
INTERVIEW_PROMPT_CACHE_TTL_SECONDS = 120
INTERVIEW_PROMPT_CACHE_MAX_ENTRIES = 256
MAX_DOC_LENGTH = 1800
MAX_TOTAL_DOCS = 5000
ENABLE_SMART_SUMMARY = True
SMART_SUMMARY_THRESHOLD = 1400
SMART_SUMMARY_TARGET = 700
SUMMARY_CACHE_ENABLED = True

# ============ 服务器配置 ============
SERVER_HOST = "0.0.0.0"
SERVER_PORT = 5001
DEBUG_MODE = True

# 列表接口分页与过载保护
LIST_API_DEFAULT_PAGE_SIZE = 20
LIST_API_MAX_PAGE_SIZE = 100
SESSIONS_LIST_MAX_INFLIGHT = 8
REPORTS_LIST_MAX_INFLIGHT = 8
LIST_API_RETRY_AFTER_SECONDS = 2

# 报告生成任务池
REPORT_GENERATION_MAX_WORKERS = 2
REPORT_GENERATION_MAX_PENDING = 16
REPORT_GENERATION_QUEUE_RETRY_AFTER_SECONDS = 3

# Gunicorn 生产配置
GUNICORN_WORKERS = 8
GUNICORN_THREADS = 2
GUNICORN_TIMEOUT = 120
GUNICORN_GRACEFUL_TIMEOUT = 30
GUNICORN_KEEPALIVE = 5
GUNICORN_WORKER_CLASS = "gthread"
GUNICORN_LOG_LEVEL = "info"

# 登录鉴权配置
SECRET_KEY = "replace-with-a-strong-random-secret"
AUTH_DB_PATH = "data/auth/users.db"

# 手机号验证码登录配置
SMS_PROVIDER = "mock"
SMS_CODE_LENGTH = 6
SMS_CODE_TTL_SECONDS = 300
SMS_SEND_COOLDOWN_SECONDS = 60
SMS_MAX_SEND_PER_PHONE_PER_DAY = 10
SMS_MAX_VERIFY_ATTEMPTS = 5
SMS_TEST_CODE = ""
SMS_CODE_SIGNING_SECRET = ""

# 京东云短信配置（SMS_PROVIDER=jdcloud 时必填）
JD_SMS_ACCESS_KEY_ID = ""
JD_SMS_ACCESS_KEY_SECRET = ""
JD_SMS_REGION_ID = "cn-north-1"
JD_SMS_SIGN_ID = ""
JD_SMS_TEMPLATE_ID_LOGIN = ""
JD_SMS_TEMPLATE_ID_BIND = ""
JD_SMS_TEMPLATE_ID_RECOVER = ""
JD_SMS_TIMEOUT = 8.0

# 场景目录配置
BUILTIN_SCENARIOS_DIR = "resources/scenarios/builtin"
CUSTOM_SCENARIOS_DIR = "~/.deepvision/scenarios/custom"

# 微信扫码登录配置（可选）
WECHAT_LOGIN_ENABLED = False
WECHAT_APP_ID = ""
WECHAT_APP_SECRET = ""
WECHAT_REDIRECT_URI = ""
INSTANCE_SCOPE_KEY = ""
WECHAT_OAUTH_SCOPE = "snsapi_login"
WECHAT_OAUTH_TIMEOUT = 8.0
WECHAT_OAUTH_STATE_TTL_SECONDS = 300

# ============ 功能开关 ============
ENABLE_AI = True
ENABLE_DEBUG_LOG = True
SUPPRESS_STATUS_POLL_ACCESS_LOG = True
ENABLE_WEB_SEARCH = True
DEEP_MODE_SKIP_FOLLOWUP_CONFIRM = True

# ============ 搜索 API 配置 ============
ZHIPU_API_KEY = "your-zhipu-api-key"
ZHIPU_SEARCH_ENGINE = "search_pro"
SEARCH_MAX_RESULTS = 3
SEARCH_TIMEOUT = 10

# ============ 图片处理配置 ============
VISION_MODEL_NAME = "glm-4v-flash"
VISION_API_URL = "https://open.bigmodel.cn/api/paas/v4/chat/completions"
ENABLE_VISION = True
MAX_IMAGE_SIZE_MB = 10
SUPPORTED_IMAGE_TYPES = ['.jpg', '.jpeg', '.png', '.gif', '.webp']

# ============ Refly API 配置 ============
REFLY_API_URL = "https://api.refly.ai/v1"
REFLY_API_KEY = "your-refly-api-key"
REFLY_WORKFLOW_ID = "replace-with-your-workflow-id"
REFLY_INPUT_FIELD = "input"
REFLY_FILES_FIELD = "files"
REFLY_TIMEOUT = 30
